/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    projects: Project;
    'process-phases': ProcessPhase;
    tenets: Tenet;
    faqs: Faq;
    clients: Client;
    posts: Post;
    authors: Author;
    submissions: Submission;
    'assessment-sessions': AssessmentSession;
    'assessment-leads': AssessmentLead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'process-phases': ProcessPhasesSelect<false> | ProcessPhasesSelect<true>;
    tenets: TenetsSelect<false> | TenetsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'assessment-sessions': AssessmentSessionsSelect<false> | AssessmentSessionsSelect<true>;
    'assessment-leads': AssessmentLeadsSelect<false> | AssessmentLeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    studio: Studio;
    contact: Contact;
    'top-bar': TopBar;
    'site-settings': SiteSetting;
    'blog-settings': BlogSetting;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    studio: StudioSelect<false> | StudioSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'top-bar': TopBarSelect<false> | TopBarSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'blog-settings': BlogSettingsSelect<false> | BlogSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Image library. Variants auto-generated on upload (thumbnail / card / hero / og).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility / SEO. Required.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Marketing pages built from blocks. The page with slug "home" renders at /. Other slugs render at /<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-safe identifier. "home" renders at /. Other values render at /<slug>.
   */
  slug: string;
  /**
   * Meta tags for this page. Falls back to title + site description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Override OG image for this page.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Drag blocks to compose the page. Add as many as you need.
   */
  layout: (
    | {
        /**
         * Small badge above headline. Optional.
         */
        pillText?: string | null;
        headline: {
          /**
           * Plain part of the headline.
           */
          lead: string;
          /**
           * Accent (electric blue) part. Optional.
           */
          accent?: string | null;
        };
        /**
         * One-paragraph subheadline below the headline.
         */
        lede?: string | null;
        /**
         * Main call-to-action button (filled).
         */
        ctaPrimary?: {
          label?: string | null;
          href?: string | null;
        };
        /**
         * Secondary CTA (outline). Optional.
         */
        ctaSecondary?: {
          label?: string | null;
          href?: string | null;
        };
        /**
         * Small stat row below CTA buttons (e.g. "3+ years jalan").
         */
        metaItems?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Show the live ops console viz on the right.
         */
        showOpsConsole?: boolean | null;
        /**
         * Show trusted-by client marquee below hero.
         */
        showTrustedBy?: boolean | null;
        trustedBy?: {
          label?: string | null;
          /**
           * Small caption next to the label.
           */
          tagline?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        sectionMarker?: string | null;
        category?: string | null;
        /**
         * Small subhead beside category, e.g. "Yang kami bangun".
         */
        description?: string | null;
        heading: string;
        lede?: string | null;
        source?: ('all' | 'manual') | null;
        services?: (number | Service)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceList';
      }
    | {
        sectionMarker?: string | null;
        category?: string | null;
        description?: string | null;
        heading: string;
        lede?: string | null;
        /**
         * Featured case shown as the big hero card. If empty, falls back to project with featured=true.
         */
        featuredProject?: (number | null) | Project;
        /**
         * Projects shown in the "more engagements" list. If empty, shows recent client projects.
         */
        listProjects?: (number | Project)[] | null;
        /**
         * Show "Lihat semua →" link to /work archive.
         */
        showViewAllLink?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'work';
      }
    | {
        sectionMarker?: string | null;
        category?: string | null;
        description?: string | null;
        heading: string;
        lede?: string | null;
        /**
         * Studio products to feature. Filtered to kind=studio at render time. If empty, all studio products are shown.
         */
        products?: (number | Project)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'products';
      }
    | {
        sectionMarker?: string | null;
        category?: string | null;
        description?: string | null;
        heading: string;
        lede?: string | null;
        /**
         * Phases to display. If empty, shows all phases sorted by order.
         */
        phases?: (number | ProcessPhase)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'process';
      }
    | {
        sectionMarker?: string | null;
        heading: string;
        lede: string;
        stats?:
          | {
              num: string;
              accent?: string | null;
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional studio note / pull quote shown below stats.
         */
        pullQuote?: {
          quote?: string | null;
          /**
           * e.g. "Coderoach Studio · Operating note"
           */
          attribution?: string | null;
        };
        /**
         * Principles shown on the right side. If empty, shows all tenets sorted by order.
         */
        tenets?: (number | Tenet)[] | null;
        fullStudioLink?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'studio';
      }
    | {
        sectionMarker?: string | null;
        category?: string | null;
        heading: string;
        lede?: string | null;
        /**
         * How many recent posts to show.
         */
        limit?: number | null;
        /**
         * Show "Lihat semua →" link to /notes archive.
         */
        showViewAllLink?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'notes';
      }
    | {
        /**
         * Small mono label above heading.
         */
        sectionMarker?: string | null;
        heading: string;
        source?: ('collection' | 'custom') | null;
        customItems?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        /**
         * Small mono label above heading.
         */
        sectionMarker?: string | null;
        heading: {
          /**
           * First line (plain).
           */
          line1: string;
          /**
           * Second line (electric blue accent).
           */
          line2Accent: string;
        };
        /**
         * Subheadline beneath the form heading.
         */
        lede: string;
        /**
         * Project type chips users can select.
         */
        scopes?:
          | {
              scope: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Form field labels, keep short.
         */
        formLabels?: {
          submit?: string | null;
          /**
           * Shown as "or email …"
           */
          emailFallback?: string | null;
        };
        successHeading?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        /**
         * Long-form content. Headings, lists, links, images.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        maxWidth?: ('narrow' | 'wide') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        /**
         * Small label above heading. Optional.
         */
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        cta?: {
          label?: string | null;
          href?: string | null;
        };
        tone?: ('dark' | 'light') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaBanner';
      }
    | {
        /**
         * Optional small label above the grid.
         */
        eyebrow?: string | null;
        heading?: string | null;
        /**
         * Each stat: big number + accent + label.
         */
        stats?:
          | {
              /**
               * e.g. "10", "100"
               */
              num: string;
              /**
               * e.g. "+", "%", "yr"
               */
              accent?: string | null;
              /**
               * Caption beneath the number.
               */
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsGrid';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Sort order in lists. Lower = earlier.
   */
  order: number;
  /**
   * URL-safe identifier, drives /services/[slug] route.
   */
  slug: string;
  /**
   * Mono label, e.g. BUILD, AUTOMATE (kept English, short tech label).
   */
  tag: string;
  icon: 'build' | 'automate' | 'intelligence' | 'augment';
  title: string;
  /**
   * Short hook (homepage card).
   */
  tagline: string;
  /**
   * Body copy on homepage card.
   */
  blurb: string;
  /**
   * Capability bullets (homepage card).
   */
  list: {
    item: string;
    id?: string | null;
  }[];
  /**
   * Tech stack pills (kept English, tech terms).
   */
  stack: {
    tech: string;
    id?: string | null;
  }[];
  /**
   * Hero copy on /services/[slug] detail page (longer than tagline).
   */
  heroLede?: string | null;
  /**
   * Full capability deep-dive (Lexical).
   */
  richContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "Engagement starts at Rp 50jt."
   */
  pricingNote?: string | null;
  /**
   * Manual pick. If empty, auto-pulled by service relationship.
   */
  caseStudies?: (number | Project)[] | null;
  /**
   * Service-scoped FAQ shown on /services/[slug].
   */
  serviceFAQ?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client cases and studio products. One collection, two kinds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * URL identifier. Auto-generated from client name.
   */
  slug: string;
  /**
   * Client = case study render. Studio = product-landing render.
   */
  kind: 'client' | 'studio';
  /**
   * Sort order in lists. Lower = earlier.
   */
  order: number;
  /**
   * Renders as homepage feature card. Only one at a time (auto-unset on others).
   */
  featured?: boolean | null;
  industry?: ('fb' | 'logistics' | 'finance' | 'agency' | 'vc' | 'manufacturing' | 'other') | null;
  /**
   * Primary service used. Drives related-projects on Service detail page.
   */
  service?: (number | null) | Service;
  /**
   * e.g. "2024", shown in "[ // SHIPPED 2024 ]" labels.
   */
  publishedYear?: string | null;
  /**
   * Client kind: company name. Studio kind: product name.
   */
  client: string;
  /**
   * One-line summary
   */
  tagline: string;
  /**
   * Industry · service tag, e.g. "F&B · INTELLIGENCE"
   */
  meta?: string | null;
  /**
   * Short summary for archive cards
   */
  excerpt?: string | null;
  /**
   * Tech pills shown on archive card / work-row
   */
  pills?:
    | {
        pill: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Full case write-up / product story (Lexical).
   */
  richContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Fill these in when this project is the homepage feature.
   */
  featuredDetails?: {
    badgeLabel?: string | null;
    shippedLabel?: string | null;
    metaLine?: string | null;
    headline?: string | null;
    description?: string | null;
    metrics?:
      | {
          num: string;
          accent?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    codePanel?: {
      tag?: string | null;
      path?: string | null;
      lines?:
        | {
            line?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    stack?:
      | {
          tech: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Studio-product specifics.
   */
  studio?: {
    vizType?: ('laporta' | 'viralytics' | 'none') | null;
    /**
     * e.g. "1.2K OUTLETS"
     */
    usage?: string | null;
    externalLink?: {
      label?: string | null;
      href?: string | null;
    };
    bullets?:
      | {
          bullet: string;
          id?: string | null;
        }[]
      | null;
  };
  coverImage?: (number | null) | Media;
  /**
   * Screenshots / diagrams
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
  };
  /**
   * Manual override. If empty, auto-pick by industry/service.
   */
  relatedProjects?: (number | Project)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-phases".
 */
export interface ProcessPhase {
  id: number;
  order: number;
  /**
   * e.g. "PHASE 01"
   */
  tag: string;
  icon: 'discover' | 'design' | 'layers' | 'handoff';
  name: string;
  what: string;
  /**
   * Deliverables line, e.g. "Source · docs · 30-day support"
   */
  deliv: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenets".
 */
export interface Tenet {
  id: number;
  order: number;
  icon: 'users' | 'voice' | 'shield';
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  order: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trusted-by marquee entries. Upload a logo for each (light variant required, dark optional).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Sort order in marquee.
   */
  order: number;
  /**
   * Brand/company name. Used as alt text and as fallback when no logo is uploaded.
   */
  name: string;
  /**
   * Logo for light backgrounds (typical Hero marquee). Recommended: SVG or transparent PNG, ~80px tall.
   */
  logo?: (number | null) | Media;
  /**
   * Optional logo variant for dark backgrounds.
   */
  logoDark?: (number | null) | Media;
  /**
   * Optional outbound URL, wraps the logo in an <a>.
   */
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * URL slug. Auto-generated from title.
   */
  slug: string;
  category: 'engineering' | 'operating' | 'studio' | 'notes';
  author: number | Author;
  publishedAt: string;
  /**
   * Pins this post to top of /notes archive.
   */
  featured?: boolean | null;
  /**
   * Auto-calculated from content (~220 words/min).
   */
  readingTime?: number | null;
  title: string;
  /**
   * Shown on archive cards & in post header.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Free-text tags. Used for filtering on /notes archive.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Hero image at top of the post.
   */
  coverImage?: (number | null) | Media;
  /**
   * Optional OG override. Falls back to coverImage if empty.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  /**
   * e.g. "Co-founder · Engineering"
   */
  role?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  socialLinks?:
    | {
        platform: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions. Public can create; only admins can read/update/delete.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  email: string;
  scope?: ('Build' | 'Automate' | 'Intelligence' | 'Augment' | 'Belum yakin' | 'Other') | null;
  brief: string;
  submittedAt?: string | null;
  status?: ('new' | 'contacted' | 'archived') | null;
  userAgent?: string | null;
  referrer?: string | null;
  /**
   * Set when the brief was sent from an OpsScore report.
   */
  assessmentSession?: (string | null) | AssessmentSession;
  /**
   * Internal notes (admin only).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One row per OpsScore attempt. Answers are stored raw so results can be recomputed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-sessions".
 */
export interface AssessmentSession {
  id: string;
  /**
   * Public /opsscore/r/[slug] link, scores only.
   */
  shareSlug: string;
  instrumentVersion: number;
  status: 'started' | 'completed' | 'gated';
  /**
   * Copy of scores.phase, for filtering.
   */
  phase?: number | null;
  /**
   * Copy of scores.total.
   */
  total?: number | null;
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  scores?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  referrer?: string | null;
  userAgent?: string | null;
  startedAt: string;
  completedAt?: string | null;
  gatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Profiles and contacts from OpsScore. Only rows with a WhatsApp number can be followed up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-leads".
 */
export interface AssessmentLead {
  id: number;
  session: string | AssessmentSession;
  name?: string | null;
  /**
   * Normalised to 62… (no plus sign), ready for wa.me links.
   */
  phoneE164?: string | null;
  brand?: string | null;
  /**
   * Optional, given at the gate.
   */
  email?: string | null;
  /**
   * Website, marketplace, or social link given during the quiz.
   */
  website?: string | null;
  industry?: ('produksi' | 'distribusi' | 'jasa' | 'retail' | 'kuliner' | 'fashion' | 'kriya' | 'lainnya') | null;
  employees?: ('1-5' | '6-10' | '11-20' | '21-50' | '51-100' | '100+') | null;
  revenueBand?: ('lt50' | '50-100' | '100-200' | '200-400' | '400-800' | 'gt800') | null;
  consentAt?: string | null;
  followupStatus: 'new' | 'contacted' | 'qualified' | 'not_fit' | 'converted';
  /**
   * Tick for test or internal sessions, so they stay out of the benchmark averages.
   */
  excludeFromBenchmark?: boolean | null;
  /**
   * This WhatsApp number already came in from another session.
   */
  repeatContact?: boolean | null;
  /**
   * Internal notes (admin only).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'process-phases';
        value: number | ProcessPhase;
      } | null)
    | ({
        relationTo: 'tenets';
        value: number | Tenet;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'assessment-sessions';
        value: string | AssessmentSession;
      } | null)
    | ({
        relationTo: 'assessment-leads';
        value: number | AssessmentLead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              pillText?: T;
              headline?:
                | T
                | {
                    lead?: T;
                    accent?: T;
                  };
              lede?: T;
              ctaPrimary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              ctaSecondary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              metaItems?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              showOpsConsole?: T;
              showTrustedBy?: T;
              trustedBy?:
                | T
                | {
                    label?: T;
                    tagline?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceList?:
          | T
          | {
              sectionMarker?: T;
              category?: T;
              description?: T;
              heading?: T;
              lede?: T;
              source?: T;
              services?: T;
              id?: T;
              blockName?: T;
            };
        work?:
          | T
          | {
              sectionMarker?: T;
              category?: T;
              description?: T;
              heading?: T;
              lede?: T;
              featuredProject?: T;
              listProjects?: T;
              showViewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        products?:
          | T
          | {
              sectionMarker?: T;
              category?: T;
              description?: T;
              heading?: T;
              lede?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              sectionMarker?: T;
              category?: T;
              description?: T;
              heading?: T;
              lede?: T;
              phases?: T;
              id?: T;
              blockName?: T;
            };
        studio?:
          | T
          | {
              sectionMarker?: T;
              heading?: T;
              lede?: T;
              stats?:
                | T
                | {
                    num?: T;
                    accent?: T;
                    label?: T;
                    id?: T;
                  };
              pullQuote?:
                | T
                | {
                    quote?: T;
                    attribution?: T;
                  };
              tenets?: T;
              fullStudioLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        notes?:
          | T
          | {
              sectionMarker?: T;
              category?: T;
              heading?: T;
              lede?: T;
              limit?: T;
              showViewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionMarker?: T;
              heading?: T;
              source?: T;
              customItems?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              sectionMarker?: T;
              heading?:
                | T
                | {
                    line1?: T;
                    line2Accent?: T;
                  };
              lede?: T;
              scopes?:
                | T
                | {
                    scope?: T;
                    id?: T;
                  };
              formLabels?:
                | T
                | {
                    submit?: T;
                    emailFallback?: T;
                  };
              successHeading?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        statsGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              stats?:
                | T
                | {
                    num?: T;
                    accent?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  order?: T;
  slug?: T;
  tag?: T;
  icon?: T;
  title?: T;
  tagline?: T;
  blurb?: T;
  list?:
    | T
    | {
        item?: T;
        id?: T;
      };
  stack?:
    | T
    | {
        tech?: T;
        id?: T;
      };
  heroLede?: T;
  richContent?: T;
  pricingNote?: T;
  caseStudies?: T;
  serviceFAQ?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  kind?: T;
  order?: T;
  featured?: T;
  industry?: T;
  service?: T;
  publishedYear?: T;
  client?: T;
  tagline?: T;
  meta?: T;
  excerpt?: T;
  pills?:
    | T
    | {
        pill?: T;
        id?: T;
      };
  richContent?: T;
  featuredDetails?:
    | T
    | {
        badgeLabel?: T;
        shippedLabel?: T;
        metaLine?: T;
        headline?: T;
        description?: T;
        metrics?:
          | T
          | {
              num?: T;
              accent?: T;
              label?: T;
              id?: T;
            };
        codePanel?:
          | T
          | {
              tag?: T;
              path?: T;
              lines?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
            };
        stack?:
          | T
          | {
              tech?: T;
              id?: T;
            };
      };
  studio?:
    | T
    | {
        vizType?: T;
        usage?: T;
        externalLink?:
          | T
          | {
              label?: T;
              href?: T;
            };
        bullets?:
          | T
          | {
              bullet?: T;
              id?: T;
            };
      };
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
      };
  relatedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-phases_select".
 */
export interface ProcessPhasesSelect<T extends boolean = true> {
  order?: T;
  tag?: T;
  icon?: T;
  name?: T;
  what?: T;
  deliv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenets_select".
 */
export interface TenetsSelect<T extends boolean = true> {
  order?: T;
  icon?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  order?: T;
  name?: T;
  logo?: T;
  logoDark?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  featured?: T;
  readingTime?: T;
  title?: T;
  excerpt?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  coverImage?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  email?: T;
  scope?: T;
  brief?: T;
  submittedAt?: T;
  status?: T;
  userAgent?: T;
  referrer?: T;
  assessmentSession?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-sessions_select".
 */
export interface AssessmentSessionsSelect<T extends boolean = true> {
  id?: T;
  shareSlug?: T;
  instrumentVersion?: T;
  status?: T;
  phase?: T;
  total?: T;
  answers?: T;
  scores?: T;
  utm?: T;
  referrer?: T;
  userAgent?: T;
  startedAt?: T;
  completedAt?: T;
  gatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-leads_select".
 */
export interface AssessmentLeadsSelect<T extends boolean = true> {
  session?: T;
  name?: T;
  phoneE164?: T;
  brand?: T;
  email?: T;
  website?: T;
  industry?: T;
  employees?: T;
  revenueBand?: T;
  consentAt?: T;
  followupStatus?: T;
  excludeFromBenchmark?: T;
  repeatContact?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  pillText: string;
  headline: {
    /**
     * Plain part, e.g. "Engineering that thinks"
     */
    lead: string;
    /**
     * Accent (electric blue) part, e.g. "like an operator."
     */
    accent: string;
  };
  lede: string;
  ctaPrimary: {
    label: string;
    href: string;
  };
  ctaSecondary?: {
    label?: string | null;
    href?: string | null;
  };
  metaItems?:
    | {
        /**
         * Bold portion, e.g. "40+", "4yr"
         */
        value: string;
        /**
         * After-text, e.g. "operators shipped"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  trustedBy?: {
    label?: string | null;
    tagline?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio".
 */
export interface Studio {
  id: number;
  sectionMarker?: string | null;
  heading: string;
  lede: string;
  stats?:
    | {
        num: string;
        /**
         * Accent suffix, e.g. "yr", "+"
         */
        accent?: string | null;
        /**
         * Two-line label, separate with newline.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * /studio page-specific fields.
   */
  about?: {
    pageHeading?: string | null;
    /**
     * Hero lede on /studio page.
     */
    pageLede?: string | null;
    /**
     * Short mission statement (1-2 sentences).
     */
    mission?: string | null;
    /**
     * Full studio narrative. Lexical.
     */
    story?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    workspace?: {
      address?: string | null;
      hours?: string | null;
      tagline?: string | null;
      image?: (number | null) | Media;
    };
    /**
     * Studio milestones.
     */
    timeline?:
      | {
          year: string;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  sectionMarker?: string | null;
  heading: {
    line1: string;
    line2Accent: string;
  };
  lede: string;
  /**
   * Scope chip options
   */
  scopes?:
    | {
        scope: string;
        id?: string | null;
      }[]
    | null;
  formLabels?: {
    email?: string | null;
    scope?: string | null;
    brief?: string | null;
    submit?: string | null;
    emailFallback?: string | null;
  };
  successHeading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top-bar".
 */
export interface TopBar {
  id: number;
  enabled?: boolean | null;
  tag?: string | null;
  message: string;
  link?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Brand name shown in nav, footer, page titles, and OG.
   */
  siteName: string;
  /**
   * Default meta description for pages without their own.
   */
  siteDescription?: string | null;
  /**
   * Primary logo (light backgrounds). Used in nav.
   */
  logo?: (number | null) | Media;
  /**
   * Logo variant for dark backgrounds (footer, dark sections). Optional.
   */
  logoDark?: (number | null) | Media;
  /**
   * Site favicon (PNG or SVG, square).
   */
  favicon?: (number | null) | Media;
  /**
   * Legacy: nav status badge (no longer rendered, kept for data continuity).
   */
  navStatus?: {
    label?: string | null;
  };
  /**
   * Primary call-to-action in the top nav.
   */
  navCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Tagline, link columns, and meta line at the bottom of every page.
   */
  footer?: {
    /**
     * Short paragraph next to the logo in footer.
     */
    tagline?: string | null;
    /**
     * Legacy: footer status badge (no longer rendered, kept for data continuity).
     */
    badge?: string | null;
    /**
     * Up to 3 footer link columns (e.g. NAVIGATE / STUDIO / CONTACT).
     */
    columns?:
      | {
          heading: string;
          links?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Small mono text below footer columns.
     */
    metaLine?: {
      left?: string | null;
      right?: string | null;
    };
  };
  /**
   * Social profiles (used in footer/contact). Platform = label, e.g. "X", "LinkedIn".
   */
  social?:
    | {
        platform: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Default Open Graph image used when a page has no specific OG image.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-settings".
 */
export interface BlogSetting {
  id: number;
  archiveHero?: {
    sectionMarker?: string | null;
    heading?: string | null;
    lede?: string | null;
  };
  postsPerPage?: number | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  pillText?: T;
  headline?:
    | T
    | {
        lead?: T;
        accent?: T;
      };
  lede?: T;
  ctaPrimary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  ctaSecondary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  metaItems?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  trustedBy?:
    | T
    | {
        label?: T;
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio_select".
 */
export interface StudioSelect<T extends boolean = true> {
  sectionMarker?: T;
  heading?: T;
  lede?: T;
  stats?:
    | T
    | {
        num?: T;
        accent?: T;
        label?: T;
        id?: T;
      };
  about?:
    | T
    | {
        pageHeading?: T;
        pageLede?: T;
        mission?: T;
        story?: T;
        workspace?:
          | T
          | {
              address?: T;
              hours?: T;
              tagline?: T;
              image?: T;
            };
        timeline?:
          | T
          | {
              year?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  sectionMarker?: T;
  heading?:
    | T
    | {
        line1?: T;
        line2Accent?: T;
      };
  lede?: T;
  scopes?:
    | T
    | {
        scope?: T;
        id?: T;
      };
  formLabels?:
    | T
    | {
        email?: T;
        scope?: T;
        brief?: T;
        submit?: T;
        emailFallback?: T;
      };
  successHeading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top-bar_select".
 */
export interface TopBarSelect<T extends boolean = true> {
  enabled?: T;
  tag?: T;
  message?: T;
  link?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  navStatus?:
    | T
    | {
        label?: T;
      };
  navCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        badge?: T;
        columns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        metaLine?:
          | T
          | {
              left?: T;
              right?: T;
            };
      };
  social?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-settings_select".
 */
export interface BlogSettingsSelect<T extends boolean = true> {
  archiveHero?:
    | T
    | {
        sectionMarker?: T;
        heading?: T;
        lede?: T;
      };
  postsPerPage?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}